[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "kaleido>=1.2.0",
    "latexify-py>=0.4.4",
    "magpylib>=5.2.1",
    "numpy>=2.3.4",
    "plotly>=6.3.1",
    "pyflowchart>=0.3.1",
    "weasyprint>=66.0",
]
